name: BobuxPlugin
main: io.github.mxylery.bobuxplugin.BobuxPlugin
version: 0.1.0

commands:
  bobuxgive:
    description: Gives the user the amount of bobux they input.
    aliases: bobuxgive
    usage: "Usage: /<command> [number]"
  bobuxitemgive:
    description: Gives the user the desired bobux item.
    aliases: bobuxitemgive
    usage: "Type: /<command> [bobuxitem]"