name: BobuxPlugin
main: io.github.mxylery.bobuxplugin.BobuxPlugin
version: 0.4.0
api-version: '1.20.5'

commands:
  bobuxgive:
    description: Gives the user the amount of bobux they input.
    aliases: bobuxgive
    usage: "Usage: /<command> [bobuxitem]"
  bobuxmenu:
    description: Opens the Bobux Menu
    aliases: bobuxmenu
    usage: "Usage: /<command>"
  bobuxinfo:
    description: Shows bobux information related to timers, etc.
    aliases: bobuxinfo
    usage: "Usage: /<command>"
  bobuxspawn:
    description: Spawns a bobux mob
    aliases: bobuxspawn
    usage: "Usage: /<command> [bobuxmob]"
  bobuxhub:
    description: Teleports user to the bobux hub
    aliases: bobuxhub
    usage: "Usage: /<command>"