name: BobuxPlugin
main: io.github.mxylery.bobuxplugin.BobuxPlugin
version: 0.3.1
api-version: '1.20.5'

commands:
  bobuxgive:
    description: Gives the user the amount of bobux they input.
    aliases: bobuxgive
    usage: "Usage: /<command> [bobuxitem]"
  bobuxmenu:
    description: Opens the Bobux Menu
    aliases: bobuxmenu
    usage: "Usage: /<command>"
  bobuxinfo:
    description: Shows bobux information related to timers, etc.
    aliases: bobuxinfo
    usage: "Usage: /<command>"